- name: debug
  debug:
    msg: "jeste dockere"

- block:
  - name: add docker-ce repository
    yum_repository:
      name: "Docker-ce"
      description: "Docker CE Stable - $basearch"
      baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
      gpgkey: "https://download.docker.com/linux/centos/gpg"
      gpgcheck: True
  - name: install docker
    yum:
      name: docker-ce
      state: installed

  - name: start docker
    service:
      name: docker
      state: started
      enabled: True
  become: True
  become_user: root
