---
- name: debug
  debug:
    msg: "jeste dockere"

- block:
    - name: add docker-ce repository
      yum_repository:
        name: "Docker-ce"
        description: "Docker CE Stable - $basearch"
        baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
        gpgkey: "https://download.docker.com/linux/centos/gpg"
        gpgcheck: true

    - name: install iptables (needed for docker)
      yum:
        name: iptables
        state: installed

    - name: install docker
      yum:
        name: docker-ce
        state: installed

    - name: start docker
      service:
        name: docker
        state: started
        enabled: true
  become: true
  become_user: root
